### PR TITLE
Check license behaviour

### PR DESCRIPTION
**Pull request by alegnaaived**
This work needs to be validated with Carolina Castro.

### CODE REVIEW

**Comment by alegnaaived** [comment]
Identificamos que no está guardando los cambios de la licencia en la última versión del EML, dado esta variable y que en el IPT-CEIBA se encuentra ajustado:
image

image

**Comment by Trjegul84** [comment]
Hello @timrobertson100 and @mike-podolskiy90, please could you tell us if there is any problem with the license change functionality of version 2.5.0 because it does not apply the selected license to the corresponding eml file. We have done many tests but it seems that when the license type is changed only the eml.xml file is modified but _eml-latestversion.xml_ is not.  
We appreciate your help.

**Comment by timrobertson100** [comment]
Thanks, @Trjegul84 
I can confirm there is no intentional change, so if that is the case it's a mistake. We'll test and explore this.

**Comment by MattBlissett** [comment]
I haven't check the behaviour in version 2.1, but I don't see a problem with 2.5.0:

Initial situation: a published dataset with two versions, all CC-BY-NC:

```
grep creative *.xml
eml-1.0.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
eml-1.1.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
eml.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
```

Change the license to CC-BY in the metadata editor and save:

```
grep creative *.xml
eml-1.0.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
eml-1.1.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
eml.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by/4.0/legalcode"><citetitle>Creative Commons Attribution (CC-BY) 4.0 License</citetitle></ulink>.</para>
```

The eml.xml has been updated, but the published versions are unchanged. Publish a new version:

```
creative *.xml
eml-1.0.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
eml-1.1.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
eml-1.2.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by/4.0/legalcode"><citetitle>Creative Commons Attribution (CC-BY) 4.0 License</citetitle></ulink>.</para>
eml.xml:    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by/4.0/legalcode"><citetitle>Creative Commons Attribution (CC-BY) 4.0 License</citetitle></ulink>.</para>
```

The new eml-1.2.xml has the changed license, and eml.xml is the same.

Metadata changes are in eml.xml (the "pending" / "pendiente" version) until the dataset is (re)published.

**Comment by Trjegul84** [comment]
@MattBlissett thanks for your answer. We understand now the behavior when we change the license type. After the change we re publish the resource and works. We will close the issue opened in the repository.

**Comment by alegnaaived** [comment]
Thank you @MattBlissett, now we understand that after edit the metadata, it will be shown if the resource is published and the eml file updated (creating a new eml version).

**Comment by Trjegul84** [comment]
> Thanks, @Trjegul84
> I can confirm there is no intentional change, so if that is the case it's a mistake. We'll test and explore this.

@timrobertson100 thank you, this has been resolved.

**Review by Trjegul84 — CHANGES_REQUESTED** [review]
The changes related to the user generate an error when you create any type of user from the admin interface.
Screenshot_20210831_204625

Screenshot_20210831_204946

**Comment by Trjegul84** [comment]
This seams to be a cache error. After clean it and restart jetty the user creation works.

**Review by Trjegul84 — APPROVED** [review]
Please omit previous review.

**Pull request merged**
